import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  LevelFormat,
  convertInchesToTwip,
} from 'docx'
import { saveAs } from 'file-saver'
import type { ItineraryShape } from '@/lib/agent/orchestrator'

export async function downloadItineraryAsDocx(
  itinerary: ItineraryShape,
  destination: string
): Promise<void> {
  const children: Paragraph[] = []

  // ── Title ──────────────────────────────────────────────────────────────────
  children.push(
    new Paragraph({
      children: [new TextRun({ text: itinerary.title, bold: true, size: 48 })],
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
    })
  )

  // ── Subtitle ───────────────────────────────────────────────────────────────
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: 'Generated by TravelGenieAI',
          color: '999999',
          size: 20,
        }),
      ],
      alignment: AlignmentType.CENTER,
    })
  )

  // ── Blank line ─────────────────────────────────────────────────────────────
  children.push(new Paragraph({ text: '' }))

  // ── Summary ────────────────────────────────────────────────────────────────
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `Destination: ${destination}  •  Duration: ${itinerary.days.length} days  •  Total Cost: $${itinerary.total_cost_usd.toLocaleString()} USD`,
          size: 22,
        }),
      ],
    })
  )
  children.push(new Paragraph({ text: '' }))

  // ── Days ───────────────────────────────────────────────────────────────────
  for (const day of itinerary.days) {
    children.push(
      new Paragraph({
        text: `Day ${day.day} — ${day.title}`,
        heading: HeadingLevel.HEADING_2,
      })
    )

    children.push(
      new Paragraph({
        children: [
          new TextRun({ text: 'Weather: ', bold: true }),
          new TextRun({ text: day.weather }),
        ],
      })
    )

    children.push(
      new Paragraph({
        children: [
          new TextRun({ text: 'Daily Budget: ', bold: true }),
          new TextRun({ text: `$${day.budget_usd}` }),
        ],
      })
    )

    for (const slot of day.slots) {
      const tipText = slot.tip ? ` — Tip: ${slot.tip}` : ''
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: `${slot.time}: `, bold: true }),
            new TextRun({ text: `${slot.activity} ($${slot.cost_usd})${tipText}` }),
          ],
          indent: { left: convertInchesToTwip(0.25) },
        })
      )
    }

    children.push(
      new Paragraph({
        children: [
          new TextRun({ text: 'Stay: ', bold: true }),
          new TextRun({
            text: `${day.accommodation.name} — $${day.accommodation.cost_usd}/night`,
          }),
        ],
        indent: { left: convertInchesToTwip(0.25) },
      })
    )

    children.push(new Paragraph({ text: '' }))
  }

  // ── Packing Tips ───────────────────────────────────────────────────────────
  if (itinerary.packing_tips.length > 0) {
    children.push(
      new Paragraph({
        text: 'Packing Tips',
        heading: HeadingLevel.HEADING_2,
      })
    )

    for (const tip of itinerary.packing_tips) {
      children.push(
        new Paragraph({
          text: tip,
          bullet: { level: 0 },
        })
      )
    }

    children.push(new Paragraph({ text: '' }))
  }

  // ── Best Time to Visit ─────────────────────────────────────────────────────
  children.push(
    new Paragraph({
      text: 'Best Time to Visit',
      heading: HeadingLevel.HEADING_2,
    })
  )
  children.push(new Paragraph({ text: itinerary.best_time_to_visit }))

  // ── Generate & Download ────────────────────────────────────────────────────
  const doc = new Document({
    numbering: {
      config: [
        {
          reference: 'bullet-numbering',
          levels: [
            {
              level: 0,
              format: LevelFormat.BULLET,
              text: '•',
              alignment: AlignmentType.LEFT,
            },
          ],
        },
      ],
    },
    sections: [{ children }],
  })

  const blob = await Packer.toBlob(doc)
  saveAs(blob, `${destination.toLowerCase().replace(/\s+/g, '-')}-itinerary.docx`)
}
